### ISSUE TITLE
`Command Summary`: Some instantiate flags don't exist

### ISSUE THREAD

**Issue by daavoo** [iterative/ldb-resources#13]
From https://github.com/iterative/ldb-resources/blob/main/documentation/Command-summary.md#instantiate--object-ids--flags. The following flags don't exist:

> --preserve-paths
> 
> Instantiate objects preserving full storage paths. Only supported for default LDB format (annotation file per every object).
> 
> --preview [lambda_id]
> 
> Preview flag instantiates data objects after passing them through a given lambda function (for example, downscaling to specific size for image previews). It has no effect if cloud storage does not support object lambdas, or code access point for lambda_id was not configured.

**Comment by volkfox** [comment]
moved to ldb repo
